# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx_compiler: [g++14, clang++18]

    env:
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: sudo apt-get install ninja-build
    
    - run: cmake --workflow --preset test

  mac:
    runs-on: macos-latest

    strategy:
      matrix:
        cxx_compiler: [clang++, g++14]

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: brew install ninja

    - run: cmake --workflow --preset test

  win-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - run: cmake --workflow --preset test

  win-mingw:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
    # need GCC install to get latest G++

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4

    - run: cmake --workflow --preset test
